name: qgroundcontrol
version: '3.2+git'
summary: Cross-platform ground control station for drones 
description: |
  QGroundControl provides full flight control and configuration for ArduPilot or PX4 Pro powered vehicles. The goal for QGroundControl is improved ease of use for new users as well as high end feature support for experienced users. 


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  qgroundcontrol:
    plugin: qmake
    qt-version: qt5
    project-files: [../../../qgroundcontrol.pro]
    source: .
    build-packages:
      - build-essential
      - qt5-default
      - qtbase5-dev-tools
      - qttools5-dev-tools
      - qtbase5-dev
      - libsdl2-dev
      - speech-dispatcher
      - libudev-dev
      - qtlocation5-dev
      - qtpositioning5-dev
      - libqt5svg5-dev
      - libqt5texttospeech5-dev
      - qtmultimedia5-dev
      - libqt5serialport5-dev
      - libqt5charts5-dev

    stage-packages:
      - libqt5gui5
    after: [desktop-qt5]
